spring.application.name=aw-chatbot
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/aw_chatbot
spring.datasource.username=aw_user
spring.datasource.password=aw_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
